-- QUERYING DATA
-- CREATING DATABASE
CREATE DATABASE TEACHER_DB;
USE TEACHER_DB;

-- CREATING TABLE 1
CREATE TABLE TEACHERS(
id INT, 
name VARCHAR(20), 
subject VARCHAR(20), 
experience CHAR(10),
salary FLOAT
);


-- CREATING THE LOG TABLE
CREATE TABLE TEACHERS_LOG(
TEACHER_ID INT,
ACTION VARCHAR(20),
TIMESTAMP TIMESTAMP DEFAULT 
CURRENT_TIMESTAMP()
);




# Create a before insert trigger named before_insert_teacher that will raise an error “salary cannot be negative” if the salary inserted to the table is less than zero. 
DELIMITER //
CREATE TRIGGER BEFORE_INSERT_TEACHER
BEFORE INSERT ON TEACHERS
FOR EACH ROW
BEGIN
IF NEW.SALARY < 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'SALARY CANNOT BE NEGATIVE';
END IF;
END;
//
DELIMITER ;


# Create an after insert trigger named after_insert_teacher 
# trigger to log the action if a new student is added
DELIMITER //
CREATE TRIGGER AFTER_INSERT_TEACHER
AFTER INSERT ON TEACHERS
FOR EACH ROW
BEGIN
INSERT INTO TEACHERS_LOG(TEACHER_ID,ACTION)
VALUES
(NEW.ID,'INSERT');
END; 



# create a before delete trigger that will raise an error when you try to delete a row with experiance greater than 10 years
DELIMITER //
CREATE TRIGGER BEFORE_DELETE_TEACHER
BEFORE DELETE ON TEACHERS
FOR EACH ROW
BEGIN
IF OLD.experiance >'10YEARS' THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANT DELETE TEACHER WITH MORE THAN 10 YEARS OF EXPERIANCE';
END IF;
END;
//
DELIMITER ;


# create a after delete trigger that will insert a row to teachers_log table when that row is deleted from teacher table  
DELIMITER //
CREATE TRIGGER AFTER_DELETE_TEACHER
AFTER DELETE ON TEACHERS
FOR EACH ROW
BEGIN
INSERT INTO TEACHERS_LOG(TEACHER_ID,ACTION,TIMESTAMP)
VALUES
(OLD.ID,'DELETE',NOW());
END ;
//
DELIMITER ;



-- INSERTING DATA TO TABLE 1
INSERT INTO TEACHERS(id , name, subject, experience, salary )
VALUE
(1,'SONA','MATHS','2YEARS','50000');
INSERT INTO TEACHERS(id , name, subject, experience, salary )
VALUES
(2,'ANU','ENGLISH','5YEARS','45000'),
(3,'MAANU','HINDI','3YEARS','40000'),
(4,'LIYA','ENGLISH','10YEARS','55000'),
(5,'ANUPRIYA','PT','6YEARS','50000'),
(6,'HANNA','BIOLOGY','1YEARS','47000'),
(7,'TREEZA','PHYSICS','4YEARS','56000'),
(8,'RAKHI','CHEMISTRY','5YEARS','40000');


SELECT *FROM  TEACHERS;
SELECT * FROM TEACHERS_LOG;


-- UPDATE
UPDATE TEACHERS SET subject ='COMPUTER' WHERE id= 8;

SELECT *FROM  TEACHERS;
SELECT * FROM TEACHERS_LOG;


-- DELETE
DELETE FROM TEACHERS WHERE ID=7;



SELECT *FROM  TEACHERS;
SELECT * FROM TEACHERS_LOG;


